# Generated by Django 5.2.9 on 2025-12-12 04:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalWorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название работы"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "hours_per_week",
                    models.IntegerField(default=2, verbose_name="Часов в неделю"),
                ),
            ],
            options={
                "verbose_name": "Тип дополнительной работы",
                "verbose_name_plural": "Типы дополнительных работ",
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(max_length=10, verbose_name="Номер аудитории"),
                ),
                ("floor", models.IntegerField(verbose_name="Этаж")),
                (
                    "capacity",
                    models.IntegerField(default=10, verbose_name="Вместимость"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Аудитория",
                "verbose_name_plural": "Аудитории",
                "ordering": ["floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название дисциплины"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код дисциплины"
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Семестр",
                    ),
                ),
                ("hours", models.IntegerField(verbose_name="Количество часов")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Дисциплина",
                "verbose_name_plural": "Дисциплины",
                "ordering": ["semester", "name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "academic_degree",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ученая степень"
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(verbose_name="Дата приема на работу"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full", "Полная ставка"),
                            ("part", "Неполная ставка"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "rate",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Ставка",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teachers/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "disciplines",
                    models.ManyToManyField(
                        blank=True,
                        to="department.discipline",
                        verbose_name="Дисциплины",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="department.classroom",
                        verbose_name="Рабочее место",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAdditionalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.additionalworktype",
                        verbose_name="Тип работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительная работа преподавателя",
                "verbose_name_plural": "Дополнительные работы преподавателей",
                "unique_together": {("teacher", "work_type")},
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="additional_works",
            field=models.ManyToManyField(
                blank=True,
                through="department.TeacherAdditionalWork",
                to="department.additionalworktype",
                verbose_name="Дополнительные работы",
            ),
        ),
    ]
