# Generated by Django 5.2.9 on 2025-12-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom",
            options={
                "ordering": ["room_number"],
                "verbose_name": "Аудитория",
                "verbose_name_plural": "Аудитории",
            },
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="floor",
        ),
        migrations.AlterField(
            model_name="classroom",
            name="capacity",
            field=models.IntegerField(default=25, verbose_name="Вместимость"),
        ),
    ]
