# Generated by Django 5.2.9 on 2025-12-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_alter_classroom_options_remove_classroom_floor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discipline",
            name="code",
        ),
    ]
